import type {
  EpistemicProvenanceManifest,
  NarrativePerspective,
} from '@endless-story/shared/types';
import type { StoryDossierEvent } from './types';

export const BORROWED_LINE_SLUG = 'borrowed-line';

export const borrowedLineEvent: StoryDossierEvent = {
  slug: BORROWED_LINE_SLUG,
  saga: '春雪社',
  day: 81,
  scene: '大世界戲臺',
  title: '別把我寫進戲裡',
  kicker: '一個人的記憶，借另一個人的嘴，落在第三個人的身上。最先看懂不對的，是一生都在替自己爭名字的小青。',
  summary:
    '《斷橋》首演，演許仙的柳生春忽然對白素貞添了一句戲本上沒有的詞。蘇映雪停了半拍，飾演小青的連翹用槍尾替她守住鑼點。第七排的金鳳聽出，那句話屬於她們最窮的那一年。滿堂卻只看見柳蘇二人的深情。',
  hero: '/handscroll/s-yunjintai-tai.jpg',
  heroAlt: '雪夜戲臺、紅色帷幕與留在案上的摺扇',
  canonFacts: [
    '《斷橋》首演由蘇映雪飾白素貞、柳生春飾許仙、連翹飾小青；金鳳持一張未署贈票人姓名的第七排四號票入場。',
    '終場前，柳生春臨場添唱：「借我一夜屋簷的人，我欠她一生不敢提名。」蘇映雪停頓一拍後答：「不敢提名，便不算還。」兩句均不在定稿戲本。',
    '連翹隨即以槍尾頓臺兩響，接小青繞場身段，樂隊重新入板，演出沒有中斷；觀眾在柳蘇對望時鼓掌。',
    '金鳳在唱詞後離開座位，十一分鐘後進入柳生春化妝間；當時蘇映雪、柳生春與連翹均在室內。',
    '金鳳說：「你們拿我的一生，唱成你們兩個的深情。」蘇映雪回答自己在台上才知道；連翹證明蘇映雪事前未排過此詞。',
    '金鳳把戲票撕成兩半，一半留在妝鏡前，一半自行帶走；當晚兩人沒有同行離開。',
    '翌日第二場演出，柳生春與蘇映雪的臨場唱詞均被撤下。修改後的戲本與半張票一同收在柳生春妝箱內。',
  ],
};

const jin: NarrativePerspective = {
  id: 'jin-feng',
  characterId: 'spring-snow:jin-feng',
  characterName: '金鳳',
  role: '霞飛路紅歌女',
  portrait: '/events/night-tuberose/jin-feng.png',
  lead: '她不是怕別人知道。她怕自己的舊日，被改成另一個人台上的深情。',
  passages: [
    {
      id: 'jin-1',
      text: '戲票是在午後送到的。信封上只寫「第七排四號」，沒有名字，字也故意寫得端正。我把它擱在妝鏡下，直到晚場開鑼前才換下紅裙。嘴上同人說去看看春雪社的新戲，心裡卻知道，我是去看她會不會再把那夜說過的話收回去。',
      claimIds: ['jin-c1', 'jin-c2'],
    },
    {
      id: 'jin-2',
      text: '柳生春演許仙，蘇映雪是白素貞，新來的連翹扮小青。第一折唱得比從前更穩，扇骨一開，滿座都跟著柳生春的腕子靜下來。我幾乎信了這張票不是她送的。直到第三折，她越過蘇映雪的水袖朝第七排停了一眼——短得旁人不會覺得有事，長得夠我把六年前都想起來。',
      claimIds: ['jin-c3'],
    },
    {
      id: 'jin-3',
      text: '「借我一夜屋簷的人，我欠她一生不敢提名。」她對著白素貞唱出來。蘇映雪停了半拍，連翹的槍尾忽然在臺上一頓、再頓，替那個空白守住鑼點。然後蘇映雪答：「不敢提名，便不算還。」全場像潮水一樣叫好。只有我知道，那句話原先沒有這麼漂亮。',
      claimIds: ['jin-c4', 'jin-c5'],
    },
    {
      id: 'jin-4',
      text: '身後兩個女學生哭得厲害，說柳老板與蘇老板那一眼絕不是演的。她們把我的屋簷當成柳生春的傷心，把蘇映雪臨場接住的那句當成兩位台柱的真情。沒有人知道燈是我守的，薑湯是我熬的，連她第二天穿走的乾衣裳也是我的。我的日子被磨亮了，卻鑲進她們兩個人的戲裡。',
      claimIds: ['jin-c6'],
    },
    {
      id: 'jin-5',
      text: '我沒等謝幕。進化妝間時，柳生春還穿著許仙的白褶子，蘇映雪只卸了一邊鬢髮，連翹抱著小青的槍站在門旁。柳生春問我的第一句竟是：「你聽見了？」那一刻我才明白，她以為這是一件禮物；蘇映雪看我的神情，卻像剛知道自己替誰收了禮。',
      claimIds: ['jin-c7', 'jin-c8'],
    },
    {
      id: 'jin-6',
      text: '我說：「你們拿我的一生，唱成你們兩個的深情。」蘇映雪立刻說，她在台上才知道那句不是唱給她。連翹也開口作證：彩排七遍，戲本裡從來沒有這兩句。我信她們。可這反而更荒唐——柳生春不只替我決定往事能不能公開，也替蘇映雪決定了，她要用白素貞的臉接住誰的愛。',
      claimIds: ['jin-c9'],
    },
    {
      id: 'jin-7',
      text: '我把票撕開，一半放在她鏡前，一半收進手袋。「這齣戲我有一半。下次要唱，先來問我。我若說不，就讓它死在屋裡。」她沒有攔。我走出大世界時雪剛落下來，忽然想起那盆晚香玉——讓一件事活著，原來也包括不把它拿給所有人看。',
      claimIds: ['jin-c10'],
    },
  ],
  claims: [
    {
      id: 'jin-c1',
      text: '金鳳收到一張未署名的第七排四號戲票，並在開演前決定赴場。',
      epistemicMode: 'observed',
      relation: 'supports',
      review: 'verified',
      evidenceRefs: ['canon:ticket', 'canon:attendance'],
    },
    {
      id: 'jin-c2',
      text: '金鳳赴場，是想確認柳生春是否會收回雨夜的承認。',
      epistemicMode: 'inferred',
      relation: 'unresolved',
      review: 'unresolved',
      evidenceRefs: ['private:jin-reason', 'seed:acknowledgement'],
    },
    {
      id: 'jin-c3',
      text: '柳生春唱到第三折時，曾特意看向金鳳所在的第七排。',
      epistemicMode: 'observed',
      relation: 'unresolved',
      review: 'contested',
      evidenceRefs: ['canon:attendance', 'private:jin-gaze'],
    },
    {
      id: 'jin-c4',
      text: '柳生春新增的唱詞，改寫自兩人第一個雨夜的私下對話。',
      epistemicMode: 'remembered',
      relation: 'reinterprets',
      review: 'contested',
      evidenceRefs: ['canon:deviation', 'seed:rain-night'],
    },
    {
      id: 'jin-c5',
      text: '柳生春曾答應成名後，第一個償還金鳳的收留。',
      epistemicMode: 'remembered',
      relation: 'unresolved',
      review: 'contested',
      evidenceRefs: ['seed:rain-night', 'seed:shared-home'],
    },
    {
      id: 'jin-c6',
      text: '金鳳認為觀眾的感動，建立在柳生春取用了本屬於兩人的生活。',
      epistemicMode: 'inferred',
      relation: 'reinterprets',
      review: 'unresolved',
      evidenceRefs: ['canon:deviation', 'private:jin-theft'],
    },
    {
      id: 'jin-c7',
      text: '金鳳在謝幕前離席，隨後進入柳生春的化妝間。',
      epistemicMode: 'observed',
      relation: 'supports',
      review: 'verified',
      evidenceRefs: ['canon:departure'],
    },
    {
      id: 'jin-c8',
      text: '柳生春把新增唱詞當作送給金鳳的禮物。',
      epistemicMode: 'inferred',
      relation: 'unresolved',
      review: 'contested',
      evidenceRefs: ['canon:confrontation', 'private:jin-gift-reading'],
    },
    {
      id: 'jin-c9',
      text: '匿名沒有保護金鳳，反而把共同往事變成柳生春一人的故事。',
      epistemicMode: 'inferred',
      relation: 'reinterprets',
      review: 'unresolved',
      evidenceRefs: ['private:jin-theft', 'seed:shared-home'],
    },
    {
      id: 'jin-c10',
      text: '金鳳留下半張票，是要求往後共享這段往事的講述權。',
      epistemicMode: 'inferred',
      relation: 'reinterprets',
      review: 'unresolved',
      evidenceRefs: ['canon:torn-ticket', 'private:jin-boundary'],
    },
  ],
};

const su: NarrativePerspective = {
  id: 'su-yingxue',
  characterId: 'spring-snow:su-yingxue',
  characterName: '蘇映雪',
  role: '白素貞 · 春雪社台柱花旦',
  portrait: '/events/sealed-watch/su-yingxue.png',
  lead: '她在台上接住了一句不屬於自己的情話，從此再也說不清那一刻是白素貞，還是蘇映雪。',
  passages: [
    {
      id: 'su-1',
      text: '《斷橋》我們整排了七遍。柳生春每一處換氣、每一步回身，我都記得；連翹的小青從哪一道鑼翻進來、槍尖停在我袖外幾寸，也錯不了。首演前她們都說我太穩，穩得像出了什麼事也能接。我沒想到，真要我接的不是戲，是別人的六年。',
      claimIds: ['su-c1'],
    },
    {
      id: 'su-2',
      text: '柳生春唱到「借我一夜屋簷的人」時，我先看見她的口形變了。那不是定稿裡的字，也不是她忘詞。她唱得太清楚，清楚得像早已在心裡排過許多次。我不知道那個人是誰，只知道她正借許仙的身子，把一樁私事遞到白素貞面前。',
      claimIds: ['su-c2', 'su-c3'],
    },
    {
      id: 'su-3',
      text: '我停了半拍。胡琴已經往下一板走，身後忽然傳來槍尾頓臺的兩聲。連翹把原定繞場提早了一步，硬替我撐出一口氣。我若照戲唱，柳生春那句便會像從未發生；我若追問，整齣戲就斷在滿堂人面前。最後我只答：「不敢提名，便不算還。」',
      claimIds: ['su-c4', 'su-c5', 'su-c6'],
    },
    {
      id: 'su-4',
      text: '那句既是替戲收口，也不是。我確實想問柳生春：你不敢提的是誰？又憑什麼要我替那個人回答？可台下先替我們回答了。掌聲起來時，她們把柳生春的眼神、我的停頓、連翹救回來的一板，全都看成柳蘇二人的情深。我望向第七排，只看見金鳳起身。',
      claimIds: ['su-c7', 'su-c8'],
    },
    {
      id: 'su-5',
      text: '金鳳進後台時說：「你們拿我的一生，唱成你們兩個的深情。」我才知道屋簷是她的。我立刻說自己在台上才知道；這話是真的，卻輕得近乎推卸。因為無論我知不知情，滿場人已經看著我的臉，替那段往事流過一次淚。',
      claimIds: ['su-c9'],
    },
    {
      id: 'su-6',
      text: '我也愛柳生春。正因如此，那一刻才更難分辨：我是在替白素貞責問許仙，替金鳳討名字，還是借別人的屋簷問自己的心？演員最擅長把真話藏進角色，可一旦真話不是自己的，唱得再真也不能算無辜。',
      claimIds: ['su-c10'],
    },
    {
      id: 'su-7',
      text: '第二日，我親手把自己添的那句也劃掉。我對柳生春說，往後別再把不屬於我的話交給我接。她問我是否生氣，我說這不是我們兩個生不生氣的事。金鳳原不原諒、那段記憶能不能再唱，都該由金鳳先開口。白素貞可以替天下人受苦，蘇映雪不能替另一個女人同意。',
      claimIds: ['su-c11'],
    },
  ],
  claims: [
    {
      id: 'su-c1',
      text: '蘇映雪與連翹在七次合排中，從未見過柳生春新增的唱詞。',
      epistemicMode: 'remembered',
      relation: 'supports',
      review: 'contested',
      evidenceRefs: ['canon:deviation', 'private:su-rehearsal'],
    },
    {
      id: 'su-c2',
      text: '蘇映雪在柳生春唱出口時，立即辨認該句不在定稿中。',
      epistemicMode: 'observed',
      relation: 'supports',
      review: 'verified',
      evidenceRefs: ['canon:deviation'],
    },
    {
      id: 'su-c3',
      text: '蘇映雪當時不知道「屋簷」指向金鳳的私人記憶。',
      epistemicMode: 'inferred',
      relation: 'unresolved',
      review: 'contested',
      evidenceRefs: ['private:su-unaware', 'seed:rain-night'],
    },
    {
      id: 'su-c4',
      text: '蘇映雪在新增唱詞後停頓了一拍。',
      epistemicMode: 'observed',
      relation: 'supports',
      review: 'verified',
      evidenceRefs: ['canon:rescue'],
    },
    {
      id: 'su-c5',
      text: '連翹以槍尾與繞場身段替蘇映雪守住了樂隊的板眼。',
      epistemicMode: 'observed',
      relation: 'supports',
      review: 'verified',
      evidenceRefs: ['canon:rescue'],
    },
    {
      id: 'su-c6',
      text: '「不敢提名，便不算還」同樣是蘇映雪的臨場添詞。',
      epistemicMode: 'observed',
      relation: 'supports',
      review: 'verified',
      evidenceRefs: ['canon:deviation'],
    },
    {
      id: 'su-c7',
      text: '蘇映雪回唱既是為了讓戲繼續，也是在質問柳生春為何不肯提名。',
      epistemicMode: 'inferred',
      relation: 'reinterprets',
      review: 'unresolved',
      evidenceRefs: ['private:su-answer', 'canon:rescue'],
    },
    {
      id: 'su-c8',
      text: '現場觀眾把四人共同造成的停頓，理解成柳生春與蘇映雪的真情流露。',
      epistemicMode: 'heard',
      relation: 'reinterprets',
      review: 'contested',
      evidenceRefs: ['canon:audience', 'canon:reviews'],
    },
    {
      id: 'su-c9',
      text: '蘇映雪在後台當面告訴金鳳，自己事前不知道添詞與屋簷記憶。',
      epistemicMode: 'observed',
      relation: 'supports',
      review: 'verified',
      evidenceRefs: ['canon:confrontation'],
    },
    {
      id: 'su-c10',
      text: '蘇映雪無法完全區分自己的回唱，是角色反應、替金鳳討名，或對柳生春的私人感情。',
      epistemicMode: 'inferred',
      relation: 'unresolved',
      review: 'unresolved',
      evidenceRefs: ['seed:su-love', 'private:su-role-confusion'],
    },
    {
      id: 'su-c11',
      text: '蘇映雪撤下自己的添詞，是拒絕再替金鳳同意公開共同記憶。',
      epistemicMode: 'inferred',
      relation: 'reinterprets',
      review: 'unresolved',
      evidenceRefs: ['canon:revision', 'private:su-boundary'],
    },
  ],
};

const lian: NarrativePerspective = {
  id: 'lian-qiao',
  characterId: 'spring-snow:lian-qiao',
  characterName: '連翹',
  role: '小青 · 新搭班刀馬旦',
  portrait: '/events/borrowed-line/lian-qiao.png',
  lead: '她救回了那一拍，報紙卻沒有寫她。也因此，她比任何人都明白「沒有名字」不是保護。',
  passages: [
    {
      id: 'lian-1',
      text: '這是我進春雪社以後，名字第一次印在大世界的戲單上。雖然只在蘇映雪與柳生春下面，雖然小青那段武戲是我自己一寸一寸爭來的，我仍把那張戲單折好，塞進貼胸的衣襟。從前我替人摔得再重，台下只知道主角打得精彩。這一晚，我想讓上海記住連翹。',
      claimIds: ['lian-c1', 'lian-c2'],
    },
    {
      id: 'lian-2',
      text: '《斷橋》排過七遍，柳生春那口氣一提，我便知道不對。她沒有忘詞；忘詞的人眼神會找鑼鼓，她卻直直看過蘇師姐的肩，落到第七排。蘇師姐水袖停在半空，連指尖都沒來得及把白素貞的鎮定找回來。',
      claimIds: ['lian-c3', 'lian-c4'],
    },
    {
      id: 'lian-3',
      text: '胡琴已經往下走，我若不動，那一拍就會摔碎。我用槍尾頓臺兩響，把小青原在後頭的繞場提前。樂隊聽見響，順著我的腳步重新入板。這不是誰吩咐的，也來不及想對不對；武旦在台上先護住別人的落腳處，等大家站穩了，才輪得到問發生什麼。',
      claimIds: ['lian-c5', 'lian-c6'],
    },
    {
      id: 'lian-4',
      text: '蘇師姐接了一句：「不敢提名，便不算還。」我從她背後看見第七排那個穿深色旗袍的女人站起來。掌聲太響，沒有人聽見椅背彈回去的聲音。那一刻我不知道她是誰，只知道台上三個人把一件事唱成了，台下有一個人卻因此走了。',
      claimIds: ['lian-c7'],
    },
    {
      id: 'lian-5',
      text: '散場後我抱著槍守在化妝間門旁。金鳳說：「你們拿我的一生，唱成你們兩個的深情。」我看見蘇師姐臉色變了，便開口說，這句彩排時從來沒有，她事前不知道。我不是替誰圓場。七遍戲我一板一眼都在，這件事我能作證。',
      claimIds: ['lian-c8'],
    },
    {
      id: 'lian-6',
      text: '金鳳說她信我們。我反而更難受。她的屋簷沒有名字，我救回來的那一拍也沒有名字。第二天三份報紙都寫柳蘇臨場唱和、情動滿堂，沒有一份寫小青為什麼忽然頓槍。原來一個人若只負責接住別人，再重的事也能被寫成主角的天分。',
      claimIds: ['lian-c9', 'lian-c10'],
    },
    {
      id: 'lian-7',
      text: '我對柳生春說：「沒問過的人，不是被你護著，是被你抹掉。」她沒有回嘴。第二場開演前，我看著蘇師姐把兩句添詞一同劃去，才重新提槍上台。小青護白娘子可以寫在戲裡；連翹替誰作證、金鳳願不願意留下，不能再由許仙一句話決定。',
      claimIds: ['lian-c11'],
    },
  ],
  claims: [
    {
      id: 'lian-c1',
      text: '連翹在首演戲單中署名飾演小青。',
      epistemicMode: 'observed',
      relation: 'supports',
      review: 'verified',
      evidenceRefs: ['canon:cast'],
    },
    {
      id: 'lian-c2',
      text: '小青的武戲是連翹為了爭取台心位置自行發展的身段。',
      epistemicMode: 'remembered',
      relation: 'supports',
      review: 'contested',
      evidenceRefs: ['seed:lian-xiaoqing', 'private:lian-work'],
    },
    {
      id: 'lian-c3',
      text: '連翹因熟悉七次合排，立即辨認柳生春臨場改詞。',
      epistemicMode: 'observed',
      relation: 'supports',
      review: 'verified',
      evidenceRefs: ['canon:deviation', 'private:su-rehearsal'],
    },
    {
      id: 'lian-c4',
      text: '連翹從蘇映雪的停袖判斷，她事前不知道柳生春會改詞。',
      epistemicMode: 'inferred',
      relation: 'unresolved',
      review: 'contested',
      evidenceRefs: ['canon:rescue', 'private:lian-read'],
    },
    {
      id: 'lian-c5',
      text: '連翹以槍尾頓臺兩響並提前繞場，使樂隊重新入板。',
      epistemicMode: 'observed',
      relation: 'supports',
      review: 'verified',
      evidenceRefs: ['canon:rescue'],
    },
    {
      id: 'lian-c6',
      text: '連翹頓槍是為了救住整齣戲，而非替柳生春的添詞助勢。',
      epistemicMode: 'inferred',
      relation: 'reinterprets',
      review: 'unresolved',
      evidenceRefs: ['private:lian-rescue', 'canon:performance'],
    },
    {
      id: 'lian-c7',
      text: '連翹在台上看見金鳳於掌聲中離開第七排。',
      epistemicMode: 'observed',
      relation: 'supports',
      review: 'verified',
      evidenceRefs: ['canon:departure'],
    },
    {
      id: 'lian-c8',
      text: '連翹以七次合排經驗，當面證明蘇映雪事前不知道添詞。',
      epistemicMode: 'observed',
      relation: 'supports',
      review: 'verified',
      evidenceRefs: ['canon:confrontation'],
    },
    {
      id: 'lian-c9',
      text: '次日三篇戲評均稱讚柳蘇臨場唱和，沒有記錄連翹救回板眼。',
      epistemicMode: 'heard',
      relation: 'supports',
      review: 'verified',
      evidenceRefs: ['canon:reviews'],
    },
    {
      id: 'lian-c10',
      text: '連翹從自身無名武行的經驗理解：匿名可能是抹除，而非保護。',
      epistemicMode: 'remembered',
      relation: 'reinterprets',
      review: 'contested',
      evidenceRefs: ['seed:lian-name', 'private:lian-name-reading'],
    },
    {
      id: 'lian-c11',
      text: '連翹認為未經詢問便匿名使用他人往事，仍是在替對方作決定。',
      epistemicMode: 'inferred',
      relation: 'reinterprets',
      review: 'unresolved',
      evidenceRefs: ['private:lian-name-reading', 'canon:revision'],
    },
  ],
};

const liu: NarrativePerspective = {
  id: 'liu-shengchun',
  characterId: 'spring-snow:liu-shengchun',
  characterName: '柳生春',
  role: '春雪社當紅坤生',
  portrait: '/events/sealed-watch/liu-shengchun-v3.png',
  lead: '她以為不說名字便是保護，直到金鳳問：那麼，為什麼全場只記得你的深情？',
  passages: [
    {
      id: 'liu-1',
      text: '那句詞是首演前三夜寫的。我把它折進戲本最末一頁，彩排時一次也沒唱。晚香玉那夜以後，我總覺得只說一句「愛過」太輕，輕得像天亮便會散。於是我託門口賣糖的小孩送去一張票，沒署名——我怕她不來，也怕她知道是我請便不肯來。',
      claimIds: ['liu-c1', 'liu-c2'],
    },
    {
      id: 'liu-2',
      text: '上台前我告訴自己，只要第七排是空的，那句就永遠留在紙上。可第一折轉身，我越過映雪的水袖，看見金鳳坐在四號位。連翹正提槍從我們身後繞場，沒有人知道我把另一齣戲藏在舌底。我忽然想讓滿城都聽見：柳生春確實欠過一個人。',
      claimIds: ['liu-c3', 'liu-c4'],
    },
    {
      id: 'liu-3',
      text: '我沒有說金鳳的名字。我甚至把「進來吧」改成「借我屋簷」，以為這樣便只剩我們認得。可我忘了，這句話不是唱向空處，是當著滿堂人交到映雪手裡。她停了一拍，連翹槍尾兩響把散掉的板眼釘回來。映雪看著我答：「不敢提名，便不算還。」我竟把她的臨場接戲也當成允許。',
      claimIds: ['liu-c5', 'liu-c6'],
    },
    {
      id: 'liu-4',
      text: '叫好聲起來，我再看，第七排已經空了。後半折我沒有錯一個身段，是連翹一路用小青的走位替我們兜住；映雪也沒有再問。謝幕時別人往台上擲花，喊的是柳蘇天生一對。我只看見四號椅背翻起來，像一扇門當著我的面合上。',
      claimIds: ['liu-c7'],
    },
    {
      id: 'liu-5',
      text: '金鳳進化妝間時，我竟然鬆了一口氣。我問她聽見沒有，本來想說的是：你看，我沒有再否認你。她卻說：「你們拿我的一生，唱成你們兩個的深情。」映雪說自己在台上才知道，連翹也替她作證。我第一個念頭仍是辯解——沒有名字，沒有人知道是你。',
      claimIds: ['liu-c8'],
    },
    {
      id: 'liu-6',
      text: '金鳳問我，今夜報紙會寫誰深情。寫柳老板與蘇老板。觀眾會記得誰救了那一拍。我以為是映雪，連翹卻在門邊說，是她先頓的槍。直到這時我才看清：我把金鳳的名字藏掉，把映雪的臉借來，把連翹救戲的力氣也吞進自己的深情裡，還以為自己只是留住了一段愛。',
      claimIds: ['liu-c9'],
    },
    {
      id: 'liu-7',
      text: '票裂開的聲音很小，比滿堂喝采更清楚。第二天映雪把自己的回唱先劃掉，我才劃去屋簷那句。連翹提著槍在旁邊等，誰也沒有替我把這件事說得好聽。半張票仍壓在妝鏡後面。若還有下一回，我得先拿著自己的半張去敲金鳳的門，也得問映雪願不願意接、連翹願不願意替我們守那一拍。',
      claimIds: ['liu-c10'],
    },
  ],
  claims: [
    {
      id: 'liu-c1',
      text: '新增唱詞由柳生春在首演前三夜寫成，且未在彩排時公開。',
      epistemicMode: 'remembered',
      relation: 'supports',
      review: 'contested',
      evidenceRefs: ['canon:deviation', 'private:liu-draft'],
    },
    {
      id: 'liu-c2',
      text: '未署名戲票是柳生春託人送給金鳳的。',
      epistemicMode: 'remembered',
      relation: 'unresolved',
      review: 'contested',
      evidenceRefs: ['canon:ticket', 'private:liu-courier'],
    },
    {
      id: 'liu-c3',
      text: '柳生春在台上確認金鳳坐在第七排四號。',
      epistemicMode: 'observed',
      relation: 'supports',
      review: 'verified',
      evidenceRefs: ['canon:attendance'],
    },
    {
      id: 'liu-c4',
      text: '柳生春添詞，是想讓自己對金鳳的虧欠進入不可抹除的公開記錄。',
      epistemicMode: 'inferred',
      relation: 'reinterprets',
      review: 'unresolved',
      evidenceRefs: ['private:liu-intent', 'seed:acknowledgement'],
    },
    {
      id: 'liu-c5',
      text: '柳生春刻意省略金鳳姓名，並改寫原話以避免旁人辨認。',
      epistemicMode: 'remembered',
      relation: 'supports',
      review: 'contested',
      evidenceRefs: ['canon:deviation', 'private:liu-draft'],
    },
    {
      id: 'liu-c6',
      text: '柳生春把金鳳沒有當場離席，誤認為她默許使用這段記憶。',
      epistemicMode: 'inferred',
      relation: 'reinterprets',
      review: 'unresolved',
      evidenceRefs: ['private:liu-permission', 'canon:departure'],
    },
    {
      id: 'liu-c7',
      text: '金鳳離席後，柳生春仍完成演出，沒有錯漏可記錄的身段。',
      epistemicMode: 'observed',
      relation: 'supports',
      review: 'verified',
      evidenceRefs: ['canon:departure', 'canon:performance'],
    },
    {
      id: 'liu-c8',
      text: '柳生春原以為匿名便足以保護金鳳。',
      epistemicMode: 'inferred',
      relation: 'reinterprets',
      review: 'unresolved',
      evidenceRefs: ['canon:confrontation', 'private:liu-intent'],
    },
    {
      id: 'liu-c9',
      text: '柳生春在爭執中理解到：匿名敘述仍可能抹除另一位當事人。',
      epistemicMode: 'inferred',
      relation: 'unresolved',
      review: 'unresolved',
      evidenceRefs: ['canon:confrontation', 'private:liu-realization'],
    },
    {
      id: 'liu-c10',
      text: '撤下唱詞，是柳生春接受金鳳對共同記憶擁有一半決定權。',
      epistemicMode: 'inferred',
      relation: 'reinterprets',
      review: 'unresolved',
      evidenceRefs: ['canon:revision', 'canon:torn-ticket', 'private:liu-realization'],
    },
  ],
};

export const borrowedLineManifest: EpistemicProvenanceManifest = {
  v: 1,
  eventId: 'spring-snow:day-81:borrowed-line',
  canonHead: 'seed://spring-snow/v1#borrowed-line',
  evidence: [
    { id: 'canon:cast', label: '正史 · 首演戲單', detail: '戲單署名蘇映雪飾白素貞、柳生春飾許仙、連翹飾小青。', visibility: 'public' },
    { id: 'canon:ticket', label: '正史 · 未署名戲票', detail: '一張第七排四號贈票送抵金鳳寓所；帳面與信封均未記錄贈票人。', visibility: 'public' },
    { id: 'canon:attendance', label: '正史 · 第七排四號', detail: '票根及帶位記錄證明金鳳本人持票入場，並坐在指定座位。', visibility: 'public' },
    { id: 'canon:deviation', label: '正史 · 兩句臨場添詞', detail: '柳生春的「借我一夜屋簷」與蘇映雪的「不敢提名，便不算還」均不在定稿和彩排抄本中。', visibility: 'public', anchor: 'seed://spring-snow/performance/斷橋/首演添詞' },
    { id: 'canon:rescue', label: '正史 · 小青救板', detail: '蘇映雪停頓一拍；連翹以槍尾頓臺兩響並提前繞場，樂隊依其節點重新入板。', visibility: 'public' },
    { id: 'canon:audience', label: '正史 · 現場反應', detail: '觀眾在蘇映雪回唱、柳蘇對望時鼓掌，台下可聞「柳蘇真情」等議論。', visibility: 'public' },
    { id: 'canon:departure', label: '正史 · 謝幕前離席', detail: '金鳳在新增唱詞後離開座位，十一分鐘後進入柳生春化妝間。', visibility: 'public' },
    { id: 'canon:performance', label: '正史 · 演出完成', detail: '連翹救回板眼後，三位演員均完成餘下身段，演出沒有中斷。', visibility: 'public' },
    { id: 'canon:confrontation', label: '正史 · 四人後台', detail: '金鳳指稱自己的生活被唱成柳蘇深情；蘇映雪否認事前知情，連翹以合排經歷替她作證。', visibility: 'public' },
    { id: 'canon:reviews', label: '正史 · 次日戲評', detail: '三篇可查戲評均稱讚柳蘇臨場唱和，沒有記錄連翹的頓槍與繞場。', visibility: 'public' },
    { id: 'canon:torn-ticket', label: '正史 · 一票兩半', detail: '戲票被撕成兩半；一半留在妝鏡前，另一半由金鳳帶走。', visibility: 'public', anchor: 'seed://spring-snow/object/第七排四號半票' },
    { id: 'canon:revision', label: '正史 · 次日撤詞', detail: '第二場恢復定稿；柳蘇兩句添詞均被劃去，半張票收進柳生春妝箱。', visibility: 'public' },
    { id: 'seed:rain-night', label: '共同記憶 · 第一夜屋簷', detail: '柳生春與金鳳都保有雨夜收留的記憶，但對原話及承諾並無共同記錄。', visibility: 'private', anchor: 'seed://spring-snow/characters/柳生春+金鳳/memory/雨夜' },
    { id: 'seed:shared-home', label: '共同記憶 · 未公開的生活', detail: '窄床、薑湯、乾衣與守夜只存在於柳生春與金鳳的私域記憶。', visibility: 'private', anchor: 'seed://spring-snow/characters/柳生春+金鳳/memory/半個家' },
    { id: 'seed:acknowledgement', label: '前事 · 晚香玉雨夜', detail: '柳生春曾當面承認愛過金鳳；金鳳要的是承認，而非必然復合。', visibility: 'private', anchor: 'seed://spring-snow/v1#night-tuberose' },
    { id: 'seed:su-love', label: '蘇映雪記憶 · 戲外真心', detail: '蘇映雪對柳生春的感情長期藏在師姐身分與生旦搭檔之下。', visibility: 'private', anchor: 'seed://spring-snow/character/蘇映雪/memory/柳生春' },
    { id: 'seed:lian-name', label: '連翹記憶 · 沒有姓的人', detail: '連翹幼時被雜技班收留，名字得靠自己在戲單上一筆一筆掙回來。', visibility: 'private', anchor: 'seed://spring-snow/character/連翹/memory/名字' },
    { id: 'seed:lian-xiaoqing', label: '連翹記憶 · 爭來的小青', detail: '小青的台心武戲來自連翹對「不能只做陪襯」的長期要求。', visibility: 'private', anchor: 'seed://spring-snow/production/斷橋/小青' },
    { id: 'private:jin-reason', label: '金鳳 · 為何赴場', detail: '她說自己是去確認承認會不會被收回；外部記錄只能證明她入場。', visibility: 'private' },
    { id: 'private:jin-gaze', label: '金鳳 · 台上一眼', detail: '金鳳認為柳生春特意越過蘇映雪望向她；舞臺視線無法由座位記錄驗證。', visibility: 'private' },
    { id: 'private:jin-theft', label: '金鳳 · 被取走的故事', detail: '她將現場看成自己的生活被轉化為柳蘇二人的舞臺深情。', visibility: 'private' },
    { id: 'private:jin-gift-reading', label: '金鳳 · 所謂禮物', detail: '柳生春問「你聽見了」，被金鳳解讀為期待她接受這份公開告白。', visibility: 'private' },
    { id: 'private:jin-boundary', label: '金鳳 · 半張票的界線', detail: '她把撕票解釋為共同記憶必須由雙方共同決定是否公開。', visibility: 'private' },
    { id: 'private:su-rehearsal', label: '蘇映雪 · 七次合排', detail: '她與連翹都記得七次合排中沒有兩句添詞；合排抄本僅能證明定稿版本。', visibility: 'private' },
    { id: 'private:su-unaware', label: '蘇映雪 · 不知屋簷', detail: '她說自己直到金鳳進後台才知道屋簷記憶的主人。', visibility: 'private' },
    { id: 'private:su-answer', label: '蘇映雪 · 為何回唱', detail: '她把回唱解釋為同時救戲與質問匿名，兩種動機無法由現場記錄分離。', visibility: 'private' },
    { id: 'private:su-role-confusion', label: '蘇映雪 · 角色與真心', detail: '她無法確定回唱中有多少來自白素貞、替金鳳討名或自己的愛。', visibility: 'private' },
    { id: 'private:su-boundary', label: '蘇映雪 · 不替人同意', detail: '她撤詞是為拒絕再以自己的角色替金鳳同意公開。', visibility: 'private' },
    { id: 'private:lian-work', label: '連翹 · 一寸寸爭來', detail: '連翹認為小青亮相來自自己持續爭取，正式製作記錄只載最終身段。', visibility: 'private' },
    { id: 'private:lian-read', label: '連翹 · 停袖的判斷', detail: '她從蘇映雪的停袖判斷對方不知情，這是舞臺經驗形成的推論。', visibility: 'private' },
    { id: 'private:lian-rescue', label: '連翹 · 頓槍動機', detail: '她說自己只想護住板眼與同臺演員，並非替添詞製造效果。', visibility: 'private' },
    { id: 'private:lian-name-reading', label: '連翹 · 匿名即抹除', detail: '她以自身長期無名的經驗，把沒有署名理解為被主角吸收，而非受到保護。', visibility: 'private' },
    { id: 'private:liu-draft', label: '柳生春 · 藏起的添詞', detail: '她自述在首演前三夜寫詞並避開彩排；現存稿紙沒有可核日期。', visibility: 'private' },
    { id: 'private:liu-courier', label: '柳生春 · 送票經過', detail: '她說票由門口孩童代送，未找到可核驗的送票證人。', visibility: 'private' },
    { id: 'private:liu-intent', label: '柳生春 · 想留下什麼', detail: '她認為添詞是讓虧欠留下公開痕跡，匿名則是對金鳳的保護。', visibility: 'private' },
    { id: 'private:liu-permission', label: '柳生春 · 誤認的允許', detail: '她把金鳳未立即離席與蘇映雪臨場回唱都理解為默許。', visibility: 'private' },
    { id: 'private:liu-realization', label: '柳生春 · 爭執後的理解', detail: '她說自己終於明白，自己同時借用了金鳳的記憶、蘇映雪的臉與連翹救戲的力氣。', visibility: 'private' },
  ],
  perspectives: [jin, su, lian, liu],
};

export const BORROWED_LINE_PERSPECTIVE_COUNT = borrowedLineManifest.perspectives.length;
